services:
  vpn-gateway:
    build:
      context: ..
      dockerfile: openvpn-gw/Dockerfile
    container_name: vpn-gateway
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - ../env/openvpn.env
    volumes:
      - /opt/openvpn-configs:/opt/openvpn-configs:ro
      - /opt/abb-docker/state/openvpn:/var/run/openvpn
    sysctls:
      net.ipv4.ip_forward: '1'
      net.ipv4.conf.all.src_valid_mark: '1'
    restart: unless-stopped

  openvpn-gw-client:
    image: curlimages/curl:8.10.1
    container_name: openvpn-gw-client
    profiles:
      - example
    network_mode: "service:vpn-gateway"
    depends_on:
      - vpn-gateway
    entrypoint: ["sleep", "infinity"]
