version: "3.8"

services:
  cewl:
    image: ghcr.io/digininja/cewl:latest
    container_name: cewl
    network_mode: "container:vpn-gateway"
    volumes:
      - ${CEWL_WORKDIR:-/opt/abb-docker/data/cewl}:/host
    working_dir: /host
    entrypoint: ["cewl"]
