version: "3.8"

services:
  feroxbuster:
    image: epi052/feroxbuster:latest
    container_name: feroxbuster
    network_mode: "container:wg-vpn"
    volumes:
      - ${FEROX_CONFIG_DIR:-/opt/abb-docker/data/feroxbuster/config}:/root/.config/feroxbuster
      - ${FEROX_OUTPUT_DIR:-/opt/abb-docker/data/feroxbuster/output}:/data
    working_dir: /data
    entrypoint: ["feroxbuster"]
