version: "3.8"

services:
  asnlookup:
    build:
      context: ../images/asnlookup
    container_name: asnlookup
    network_mode: "container:vpn-gateway"
    volumes:
      - ${ASNLOOKUP_OUTPUT:-/opt/abb-docker/data/asnlookup}:/workspace
    working_dir: /workspace
    tty: true
