version: "3.8"

services:
  dnsvalidator:
    build:
      context: ../images/dnsvalidator
    container_name: dnsvalidator
    volumes:
      - ${DNSVALIDATOR_OUTPUT:-/opt/abb-docker/data/dnsvalidator}:/dnsvalidator/output
    working_dir: /dnsvalidator/output
    tty: true
