services:
  vpn-gateway:
    image: qmcgaw/gluetun:latest
    container_name: vpn-gateway
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - ../env/protonvpn-gluetun.env
    volumes:
      - /opt/abb-docker/state/gluetun:/gluetun
    restart: unless-stopped
